/* ============================================================
   ECG1 2026-2027 — Manifeste du site
   Utilisé pour : recherche globale, barres de progression,
   marquage "terminé" dans les sommaires.
   Chaque page : id (clé localStorage), m (matière), t (titre),
   u (URL relative à la racine), s (sections pour la recherche).
   ============================================================ */

const SITE_DATA = {
  matieres: {
    maths:    { name: "Mathématiques appliquées & informatique", color: "#2563eb", index: "maths/index.html" },
    esh:      { name: "ESH — Économie, sociologie, histoire",    color: "#0f8a6d", index: "esh/index.html" },
    cg:       { name: "Culture générale",                        color: "#7c3aed", index: "culture-generale/index.html" },
    anglais:  { name: "LVA Anglais",                             color: "#c0264b", index: "anglais/index.html" },
    italien:  { name: "LVB Italien",                             color: "#d97706", index: "italien/index.html" },
    methodo:  { name: "Méthodologie & concours",                 color: "#475569", index: "methodologie/index.html" }
  },

  pages: [
    /* ---------- Mathématiques appliquées — Semestre 1 ---------- */
    { id: "maths-ch01", m: "maths", n: "1", t: "Raisonnement et vocabulaire ensembliste", u: "maths/ch01-logique-ensembles.html",
      s: ["Logique et propositions", "Quantificateurs", "Types de raisonnement", "Récurrence", "Ensembles", "Applications, injections, surjections"] },
    { id: "maths-ch02", m: "maths", n: "2", t: "Calculs algébriques : sommes, produits, binôme", u: "maths/ch02-calculs-algebriques.html",
      s: ["Symboles somme et produit", "Sommes usuelles", "Sommes télescopiques", "Factorielles", "Coefficients binomiaux", "Formule du binôme de Newton"] },
    { id: "maths-ch03", m: "maths", n: "3", t: "Nombres réels, équations et inéquations", u: "maths/ch03-nombres-reels.html",
      s: ["L'ensemble des réels", "Intervalles", "Valeur absolue", "Puissances et racines", "Trinôme du second degré", "Inéquations et tableaux de signes"] },
    { id: "maths-ch04", m: "maths", n: "4", t: "Systèmes linéaires et pivot de Gauss", u: "maths/ch04-systemes-lineaires.html",
      s: ["Vocabulaire des systèmes", "Opérations élémentaires", "Méthode du pivot de Gauss", "Systèmes échelonnés", "Systèmes avec paramètre"] },
    { id: "maths-ch05", m: "maths", n: "5", t: "Calcul matriciel", u: "maths/ch05-calcul-matriciel.html",
      s: ["Définitions et matrices particulières", "Opérations sur les matrices", "Produit matriciel", "Matrices inversibles", "Puissances de matrices", "Formule du binôme matriciel"] },
    { id: "maths-ch06", m: "maths", n: "6", t: "Suites réelles", u: "maths/ch06-suites.html",
      s: ["Généralités et monotonie", "Suites arithmétiques et géométriques", "Suites arithmético-géométriques", "Récurrences linéaires d'ordre 2", "Limites de suites", "Théorèmes de convergence", "Croissances comparées"] },
    { id: "maths-ch07", m: "maths", n: "7", t: "Fonctions réelles : limites, continuité, fonctions usuelles", u: "maths/ch07-fonctions.html",
      s: ["Généralités sur les fonctions", "Limites de fonctions", "Continuité", "Théorème des valeurs intermédiaires", "Logarithme et exponentielle", "Fonctions puissances", "Valeur absolue et partie entière"] },
    { id: "maths-ch08", m: "maths", n: "8", t: "Dérivation, étude de fonctions et convexité", u: "maths/ch08-derivation.html",
      s: ["Nombre dérivé et fonction dérivée", "Opérations sur les dérivées", "Dérivée et variations", "Extremums", "Plan d'étude d'une fonction", "Convexité et inégalités"] },
    { id: "maths-ch09", m: "maths", n: "9", t: "Dénombrement", u: "maths/ch09-denombrement.html",
      s: ["Principes additif et multiplicatif", "Listes et arrangements", "Permutations", "Combinaisons", "Modèles d'urnes", "Méthodes de dénombrement"] },
    { id: "maths-ch10", m: "maths", n: "10", t: "Espaces probabilisés finis", u: "maths/ch10-probabilites-finies.html",
      s: ["Vocabulaire des événements", "Probabilité sur un univers fini", "Équiprobabilité", "Probabilités conditionnelles", "Formule des probabilités totales", "Formule de Bayes", "Indépendance"] },

    /* ---------- Mathématiques appliquées — Semestre 2 ---------- */
    { id: "maths-ch11", m: "maths", n: "11", t: "Variables aléatoires finies et lois usuelles", u: "maths/ch11-variables-aleatoires.html",
      s: ["Variable aléatoire et loi", "Fonction de répartition", "Espérance", "Théorème de transfert", "Variance et écart-type", "Loi uniforme", "Loi de Bernoulli", "Loi binomiale"] },
    { id: "maths-ch12", m: "maths", n: "12", t: "Intégration sur un segment", u: "maths/ch12-integration.html",
      s: ["Primitives", "Primitives usuelles", "Intégrale et aire", "Propriétés de l'intégrale", "Intégration par parties", "Sommes de Riemann"] },
    { id: "maths-ch13", m: "maths", n: "13", t: "Séries numériques", u: "maths/ch13-series.html",
      s: ["Convergence d'une série", "Séries géométriques et dérivées", "Séries de Riemann", "Séries à termes positifs", "Série exponentielle", "Convergence absolue"] },
    { id: "maths-ch14", m: "maths", n: "14", t: "Probabilités sur un univers dénombrable, lois géométrique et de Poisson", u: "maths/ch14-probabilites-denombrables.html",
      s: ["Tribus et probabilités", "Continuité monotone", "Variables aléatoires discrètes", "Loi géométrique", "Loi de Poisson", "Approximation binomiale-Poisson"] },
    { id: "maths-ch15", m: "maths", n: "15", t: "Couples de variables aléatoires finies", u: "maths/ch15-couples-va.html",
      s: ["Loi conjointe", "Lois marginales", "Lois conditionnelles", "Indépendance de variables aléatoires", "Covariance", "Espérance d'une somme et d'un produit"] },
    { id: "maths-ch16", m: "maths", n: "16", t: "Introduction aux graphes", u: "maths/ch16-graphes.html",
      s: ["Vocabulaire des graphes", "Degrés et lemme des poignées de main", "Matrice d'adjacence", "Chemins et connexité", "Nombre de chemins de longueur donnée"] },
    { id: "maths-ch17", m: "maths", n: "17", t: "Statistiques descriptives", u: "maths/ch17-statistiques.html",
      s: ["Vocabulaire statistique", "Indicateurs de position", "Indicateurs de dispersion", "Statistiques bivariées", "Covariance et corrélation", "Ajustement affine et droite des moindres carrés"] },

    /* ---------- Informatique (Python) ---------- */
    { id: "maths-info01", m: "maths", n: "I1", t: "Python : bases du langage", u: "maths/info01-bases-python.html",
      s: ["Variables et types", "Opérateurs", "Conditions", "Boucles for et while", "Fonctions", "Erreurs classiques"] },
    { id: "maths-info02", m: "maths", n: "I2", t: "Python : listes et manipulation de données", u: "maths/info02-listes.html",
      s: ["Créer et parcourir des listes", "Slicing", "Listes en compréhension", "Méthodes de listes", "Chaînes de caractères"] },
    { id: "maths-info03", m: "maths", n: "I3", t: "Python : numpy, matplotlib et random", u: "maths/info03-numpy-matplotlib.html",
      s: ["Tableaux numpy", "Opérations vectorisées", "Matrices avec numpy", "Graphiques matplotlib", "Module random"] },
    { id: "maths-info04", m: "maths", n: "I4", t: "Python : simulation et méthode de Monte-Carlo", u: "maths/info04-simulation.html",
      s: ["Simuler une expérience aléatoire", "Fréquences et loi des grands nombres", "Méthode de Monte-Carlo", "Simulation de lois usuelles"] },
    { id: "maths-info05", m: "maths", n: "I5", t: "Python : suites, seuil et dichotomie", u: "maths/info05-algorithmes.html",
      s: ["Calcul des termes d'une suite", "Algorithmes de seuil", "Dichotomie", "Complexité et bonnes pratiques"] },
    { id: "maths-formulaire", m: "maths", r: true, n: "", t: "Formulaire / Mémo — toutes les formules de maths", u: "maths/formulaire.html",
      s: ["Formules d'algèbre et de calcul", "Analyse et intégration", "Probabilités et lois usuelles", "Séries, graphes, statistiques", "Mémo Python"] },
    { id: "maths-flashcards", m: "maths", r: true, n: "", t: "Flashcards Maths", u: "maths/flashcards.html",
      s: ["Répétition espacée", "Formules et théorèmes", "Méthodes types", "Lois de probabilité"] },
    { id: "maths-annales", m: "maths", r: true, n: "", t: "Annales BCE / Ecricome — maths appliquées", u: "maths/annales.html",
      s: ["Sujets de concours", "Gabarit de corrigé"] },

    /* ---------- ESH — Module 1 ---------- */
    { id: "esh-ch01", m: "esh", n: "1.1", t: "Qu'est-ce que l'économie ? Objets, méthodes et grands courants", u: "esh/ch01-science-economique.html",
      s: ["La science économique : définitions", "Méthodes de l'économie", "Les classiques", "Les néoclassiques", "Keynes et la macroéconomie", "Courants contemporains"] },
    { id: "esh-ch02", m: "esh", n: "1.2", t: "Qu'est-ce que la sociologie ? Objets, méthodes et auteurs fondateurs", u: "esh/ch02-sociologie.html",
      s: ["La naissance de la sociologie", "Durkheim et le fait social", "Weber et l'action sociale", "Marx", "Bourdieu", "Méthodes quantitatives et qualitatives", "Holisme et individualisme"] },
    { id: "esh-ch03", m: "esh", n: "1.3", t: "Le fonctionnement du marché", u: "esh/ch03-marche.html",
      s: ["Offre et demande", "Équilibre de marché", "Élasticités", "Concurrence parfaite", "Monopole et oligopole", "Défaillances du marché", "Externalités et biens publics"] },
    { id: "esh-ch04", m: "esh", n: "1.4", t: "Monnaie et financement de l'économie", u: "esh/ch04-monnaie-financement.html",
      s: ["Fonctions et formes de la monnaie", "Création monétaire", "Banque centrale et politique monétaire", "Financement de l'économie", "Marchés financiers", "Intermédiation"] },
    { id: "esh-ch05", m: "esh", n: "1.5", t: "Les acteurs et les grandes fonctions économiques", u: "esh/ch05-acteurs-comptabilite.html",
      s: ["Secteurs institutionnels", "Circuit économique", "PIB et ses limites", "Consommation et épargne", "Investissement", "Comptabilité nationale"] },
    { id: "esh-ch06", m: "esh", n: "1.6", t: "Socialisation, normes, déviance et stratification sociale", u: "esh/ch06-socialisation-stratification.html",
      s: ["La socialisation", "Normes et déviance", "Stratification sociale", "Les classes sociales chez Marx et Weber", "Les PCS", "Moyennisation et distinction"] },

    /* ---------- ESH — Module 2 ---------- */
    { id: "esh-ch07", m: "esh", n: "2.1", t: "La croissance économique : mesure, facteurs, théories", u: "esh/ch07-croissance.html",
      s: ["Mesurer la croissance", "Les révolutions industrielles", "Facteurs de croissance", "Modèle de Solow", "Croissance endogène", "Institutions et croissance"] },
    { id: "esh-ch08", m: "esh", n: "2.2", t: "Croissance, progrès technique et emploi", u: "esh/ch08-progres-technique-emploi.html",
      s: ["Le progrès technique", "Schumpeter et l'innovation", "Destruction créatrice", "Progrès technique et emploi", "Déversement", "Polarisation du marché du travail"] },
    { id: "esh-ch09", m: "esh", n: "2.3", t: "Développement, inégalités et soutenabilité", u: "esh/ch09-developpement-inegalites.html",
      s: ["Croissance et développement", "IDH et indicateurs", "Inégalités et courbe de Kuznets", "Limites écologiques", "Développement durable", "Soutenabilité faible et forte"] },
    { id: "esh-ch10", m: "esh", n: "2.4", t: "Transformations économiques, sociales et démographiques depuis le XIXe siècle", u: "esh/ch10-transformations-structures.html",
      s: ["Transition démographique", "Tertiarisation", "Salarisation", "Urbanisation", "Transformation des classes sociales", "Place des femmes"] },
    { id: "esh-ch11", m: "esh", n: "2.5", t: "Entreprises et organisations", u: "esh/ch11-entreprises-organisations.html",
      s: ["Histoire de l'entreprise", "Théories de la firme", "Coase et Williamson", "Relation d'agence", "Gouvernance d'entreprise", "Formes d'organisation du travail"] },
    { id: "esh-ch12", m: "esh", n: "2.6", t: "Fluctuations et crises depuis le XIXe siècle", u: "esh/ch12-fluctuations-crises.html",
      s: ["Cycles économiques", "La crise de 1873", "La crise de 1929", "Le choc de 1973", "La crise de 2008", "Théories des crises", "Politiques de sortie de crise"] },
    { id: "esh-formulaire", m: "esh", r: true, n: "", t: "Formulaire / Mémo — tout le programme d'ESH", u: "esh/formulaire.html",
      s: ["Fiches de révision condensées", "Auteurs et dates clés", "Chiffres clés", "Mécanismes clés"] },
    { id: "esh-flashcards", m: "esh", r: true, n: "", t: "Flashcards ESH", u: "esh/flashcards.html",
      s: ["Répétition espacée", "Auteurs et dates", "Chiffres clés", "Définitions"] },
    { id: "esh-annales", m: "esh", r: true, n: "", t: "Annales BCE / Ecricome — ESH", u: "esh/annales.html",
      s: ["Sujets de concours", "Gabarit de corrigé"] },

    /* ---------- Culture générale ---------- */
    { id: "cg-methodo-dissert", m: "cg", n: "M1", t: "Méthodologie de la dissertation de culture générale", u: "culture-generale/methodologie-dissertation.html",
      s: ["Analyser le sujet", "Problématiser", "Construire un plan", "Introduction et conclusion", "L'usage des références", "Exemple commenté"] },
    { id: "cg-methodo-contraction", m: "cg", n: "M2", t: "Méthodologie de la contraction et de la synthèse de texte", u: "culture-generale/methodologie-contraction.html",
      s: ["Les épreuves de contraction", "Lire et structurer le texte", "Règles de réécriture", "Gestion du nombre de mots", "Exemple corrigé de contraction", "La synthèse de textes"] },
    { id: "cg-nature", m: "cg", n: "1", t: "La nature et la culture", u: "culture-generale/nature-culture.html",
      s: ["Définitions et problématiques", "L'état de nature", "Nature humaine et culture", "Philosophes essentiels", "Œuvres littéraires", "Sujets de dissertation"] },
    { id: "cg-societe", m: "cg", n: "2", t: "La société", u: "culture-generale/societe.html",
      s: ["L'homme animal politique", "Contrat social", "Lien social", "Individu et société", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-technique", m: "cg", n: "3", t: "La technique", u: "culture-generale/technique.html",
      s: ["Prométhée et l'origine de la technique", "La technique comme libération", "Critiques de la technique", "Heidegger", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-religion", m: "cg", n: "4", t: "La religion", u: "culture-generale/religion.html",
      s: ["Étymologies et définitions", "Preuves et critiques de l'existence de Dieu", "Religion et société", "La sécularisation", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-histoire", m: "cg", n: "5", t: "L'histoire", u: "culture-generale/histoire.html",
      s: ["Histoire vécue et histoire écrite", "Le sens de l'histoire", "Hegel et Marx", "La critique des philosophies de l'histoire", "Mémoire et histoire", "Sujets corrigés"] },
    { id: "cg-liberte", m: "cg", n: "6", t: "La liberté", u: "culture-generale/liberte.html",
      s: ["Libre arbitre et déterminisme", "Liberté politique", "Le stoïcisme", "Sartre et l'existentialisme", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-desir", m: "cg", n: "7", t: "Le désir", u: "culture-generale/desir.html",
      s: ["Désir et manque chez Platon", "Épicure et la limitation des désirs", "Spinoza et le désir comme essence", "Le désir mimétique", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-art", m: "cg", n: "8", t: "L'art", u: "culture-generale/art.html",
      s: ["Art et imitation", "Le beau chez Kant", "L'art comme révélation", "Hegel et la mort de l'art", "L'art contemporain", "Sujets corrigés"] },
    { id: "cg-verite", m: "cg", n: "9", t: "La vérité", u: "culture-generale/verite.html",
      s: ["Définitions de la vérité", "Scepticisme", "Descartes et l'évidence", "Vérité et interprétation chez Nietzsche", "Vérité et sciences", "Sujets corrigés"] },
    { id: "cg-science", m: "cg", n: "10", t: "La science", u: "culture-generale/science.html",
      s: ["La révolution scientifique", "Méthode expérimentale", "Popper et la falsifiabilité", "Kuhn et les paradigmes", "Science et technique", "Sujets corrigés"] },
    { id: "cg-langage", m: "cg", n: "11", t: "Le langage", u: "culture-generale/langage.html",
      s: ["Langage et pensée", "Le signe linguistique", "Langage et pouvoir", "Rhétorique et sophistique", "Références littéraires", "Sujets corrigés"] },
    { id: "cg-mort", m: "cg", n: "12", t: "La mort", u: "culture-generale/mort.html",
      s: ["Épicure et la mort", "L'être-pour-la-mort", "La mort dans la littérature", "Immortalité et finitude", "Sujets corrigés"] },
    { id: "cg-amour", m: "cg", n: "13", t: "L'amour", u: "culture-generale/amour.html",
      s: ["Éros, philia, agapè", "Le Banquet de Platon", "Amour-passion et cristallisation", "L'amour dans la littérature", "Sujets corrigés"] },

    /* ---------- LVA Anglais ---------- */
    { id: "anglais-civi", m: "anglais", n: "1", t: "Civilisation : États-Unis et Royaume-Uni", u: "anglais/civilisation.html",
      s: ["Institutions américaines", "Institutions britanniques", "Société américaine", "Société britannique", "Économie", "Environnement", "Technologie et médias"] },
    { id: "anglais-gram", m: "anglais", n: "2", t: "Grammaire anglaise : les points essentiels", u: "anglais/grammaire.html",
      s: ["Temps et aspects", "Les modaux", "Le passif", "Structures causatives", "Articles et déterminants", "Relatives", "Exercices corrigés"] },
    { id: "anglais-vocab", m: "anglais", n: "3", t: "Vocabulaire thématique de presse", u: "anglais/vocabulaire.html",
      s: ["Économie et entreprise", "Politique et institutions", "Société", "Environnement", "Technologie", "Verbes de presse"] },
    { id: "anglais-methodo", m: "anglais", n: "4", t: "Méthodologie des épreuves d'anglais", u: "anglais/methodologie.html",
      s: ["La version", "Le thème", "L'essai", "La synthèse", "Les khôlles orales"] },
    { id: "anglais-exos", m: "anglais", n: "5", t: "Exercices corrigés d'anglais", u: "anglais/exercices.html",
      s: ["Thèmes grammaticaux corrigés", "Versions corrigées", "Sujets d'essai avec plans", "QCM de grammaire"] },
    { id: "anglais-verbes", m: "anglais", n: "6", t: "Les verbes irréguliers anglais", u: "anglais/verbes-irreguliers.html",
      s: ["Verbes à une forme", "Verbes à deux formes", "Verbes à trois formes", "Lie/lay/lain", "Quiz des verbes irréguliers"] },
    { id: "anglais-textes", m: "anglais", n: "7", t: "Textes littéraires complexes & version littéraire", u: "anglais/textes-litteraires.html",
      s: ["Méthode de la version littéraire", "Corpus gradué (Austen, Dickens, Poe, Conrad)", "Vocabulaire du registre littéraire", "Liste de lecture domaine public"] },
    { id: "anglais-oral", m: "anglais", n: "8", t: "Compréhension orale anglaise C1-C2", u: "anglais/comprehension-orale.html",
      s: ["Méthode d'écoute active", "Accents et connected speech", "Ressources vidéo et podcasts", "Prise de notes en écoute"] },
    { id: "anglais-toeic", m: "anglais", n: "9", t: "Préparation au TOEIC", u: "anglais/toeic.html",
      s: ["Structure et barème du TOEIC", "Listening parties 1 à 4", "Reading parties 5 à 7", "Gestion du temps", "Pièges classiques"] },
    { id: "anglais-formulaire", m: "anglais", r: true, n: "", t: "Formulaire / Mémo — anglais", u: "anglais/formulaire.html",
      s: ["Fiches de révision condensées", "Grammaire", "Civilisation", "Vocabulaire"] },
    { id: "anglais-flashcards", m: "anglais", r: true, n: "", t: "Flashcards anglais", u: "anglais/flashcards.html",
      s: ["Répétition espacée", "Grammaire", "Vocabulaire", "Civilisation"] },
    { id: "anglais-annales", m: "anglais", r: true, n: "", t: "Annales BCE / Ecricome — anglais", u: "anglais/annales.html",
      s: ["Sujets de concours", "Gabarit de corrigé"] },

    /* ---------- LVB Italien ---------- */
    { id: "italien-civi", m: "italien", n: "1", t: "Civilisation : l'Italie contemporaine", u: "italien/civilisation.html",
      s: ["Institutions italiennes", "Histoire du XXe siècle", "Nord et Sud, la question méridionale", "Économie italienne", "Mafia et société", "Migrations", "Italie et Europe"] },
    { id: "italien-gram", m: "italien", n: "2", t: "Grammaire italienne : les points essentiels", u: "italien/grammaire.html",
      s: ["Essere et avere", "Passato prossimo et imperfetto", "Le subjonctif", "Futur et conditionnel", "Pronoms ci et ne", "L'hypothèse", "Exercices corrigés"] },
    { id: "italien-vocab", m: "italien", n: "3", t: "Vocabulaire thématique italien", u: "italien/vocabulaire.html",
      s: ["Économie et travail", "Politique et société", "Environnement", "Migrations", "Technologie", "Expressions de presse", "Faux amis"] },
    { id: "italien-methodo", m: "italien", n: "4", t: "Méthodologie des épreuves d'italien", u: "italien/methodologie.html",
      s: ["La version", "Le thème", "L'essai", "Les khôlles orales"] },
    { id: "italien-exos", m: "italien", n: "5", t: "Exercices corrigés d'italien", u: "italien/exercices.html",
      s: ["Thèmes grammaticaux corrigés", "Version corrigée", "Sujets d'essai avec plans", "QCM de grammaire"] },
    { id: "italien-formulaire", m: "italien", r: true, n: "", t: "Formulaire / Mémo — italien", u: "italien/formulaire.html",
      s: ["Fiches de révision condensées", "Grammaire", "Civilisation", "Vocabulaire"] },
    { id: "italien-flashcards", m: "italien", r: true, n: "", t: "Flashcards italien", u: "italien/flashcards.html",
      s: ["Répétition espacée", "Grammaire", "Vocabulaire", "Civilisation"] },
    { id: "italien-annales", m: "italien", r: true, n: "", t: "Annales BCE / Ecricome — italien", u: "italien/annales.html",
      s: ["Sujets de concours", "Gabarit de corrigé"] },

    /* ---------- Méthodologie & concours ---------- */
    { id: "methodo-organisation", m: "methodo", n: "1", t: "Organisation du travail en prépa", u: "methodologie/organisation.html",
      s: ["Planning type d'une semaine", "Gérer les colles et les DS", "Fiches et mémorisation", "Sommeil et hygiène de vie"] },
    { id: "methodo-colles", m: "methodo", n: "2", t: "Réussir ses colles de maths et d'ESH", u: "methodologie/colles.html",
      s: ["Déroulement d'une colle de maths", "Préparer une colle de maths", "La colle d'ESH", "Gestion du stress à l'oral"] },
    { id: "methodo-concours", m: "methodo", n: "3", t: "Les concours BCE et Ecricome", u: "methodologie/concours.html",
      s: ["Présentation de la BCE", "Présentation d'Ecricome", "Les épreuves en maths appliquées", "Coefficients par école", "Les oraux"] },
    { id: "methodo-conseils", m: "methodo", n: "4", t: "Conseils pour réussir sa première année", u: "methodologie/conseils.html",
      s: ["Les erreurs classiques", "Travailler régulièrement", "Matière par matière", "Rebondir après un échec"] }
  ]
};
